### ISSUE TITLE
New way to add packs

### ISSUE THREAD

**Issue by zackshapiro** [zackshapiro/silencer#103]
``` html
<ul class="services">
        <p class="services-title">Services</p>

        <li class="service">instagram
          <div class="adder">+</div>
        </li>
        <li class="service">get glue
          <div class="adder">+</div>
          <!-- <a href="#" class="add-glue cta">Mute</a> -->
        </li>
        <li class="service">ask.fm
          <div class="adder">+</div>
          <!-- <a href="#" class="add-ask cta">Mute</a> -->
        </li>
        <li class="service">vine
          <div class="adder">+</div>
          <!-- <a href="#" class="add-vine cta">Mute</a> -->
        </li>
        <li class="service">foursquare
          <div class="adder">+</div>
          <!-- <a href="#" class="add-4sq cta">Mute</a> -->
        </li>
        <li class="service">path
          <div class="adder">+</div>
          <!-- <a href="#" class="add-path cta">Mute</a> -->
        </li>
        <li class="service">timehop
          <div class="adder">+</div>
          <!-- <a href="#" class="add-th cta">Mute</a> -->
        </li>
        <li class="service">medium
          <div class="adder">+</div>
          <!-- <a href="#" class="add-medium cta">Mute</a> -->
        </li>
        <li class="service">nike+
          <div class="adder">+</div>
          <!-- <a href="#" class="add-nike cta">Mute</a> -->
        </li>
        <li class="service">circa
          <div class="adder">+</div>
          <!-- <a href="#" class="add-circa cta">Mute</a> -->
        </li>
        <li class="service">paper.li
          <div class="adder">+</div>
          <!-- <a href="#" class="add-paper cta">Mute</a> -->
        </li>
      </ul>
    </ul>
```

**Comment by zackshapiro** [comment]
``` css

.adder {
  opacity: 0;
  position: relative;
  filter: alpha(opacity=0);
  display: inline-block;
  margin-left: -10px;
  -webkit-transition: all 0.3s ease-in-out; 
}

.service:hover .adder {
  opacity: 1;
  color: green;
  margin-left: 1px;
  filter: alpha(opacity=100);
}

```
