### ISSUE TITLE
Add pop-out twitter bird for sharing what you're muting

### ISSUE THREAD

**Issue by zackshapiro** [zackshapiro/silencer#105]
``` css
.bird {
  background-image: url("/icons/bird.png");
  background-repeat: no-repeat;
  width: 20px;
  height: 20px;
  display: inline-block;
  background-position-x: 5px;
  background-position-y: 5px;
  background-size: 20px;
  margin-right: 6px;
  margin-left: -26px;
}

```

**Comment by zackshapiro** [comment]
``` js

$("<a href='#' class='twitter-share-button sharer'></a>").insertBefore($(child).find('.remove-term'))

```

**Comment by zackshapiro** [comment]
``` css

.twitter-share-button {
  float: left;
  opacity: 0;
  filter: alpha(opacity=0);
  background-image: url("/icons/bird.png");
  background-repeat: no-repeat;
  width: 20px;
  height: 20px;
  display: inline-block;
  background-position-x: 5px;
  background-position-y: 5px;
  background-size: 20px;
  position: relative;
  margin-top: -4px;
  margin-right: -10px;
  margin-left: -12px;
  -webkit-transition: all 0.3s ease-in-out;
}

.term:hover .twitter-share-button {
  opacity: 1;
  filter: alpha(opacity=100);
  right: 13px;
}

/* Finish this */
.twitter-share-button:hover .removal{
  display: none !important;
}

```
